spring:
  application:
    name: config-server-uat


eureka:         #tells about the Eureka server details and its refresh time
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  
